window.MUAMMER_TOPICS = [
  ['Leadership', 0, 'primary', 0.12, 0.18, 'Setting a shared direction.'],
  [
    'Strategy',
    0,
    'primary',
    0.48,
    0.1,
    'Thinking about technology and business objectives together.',
  ],
  [
    'value creation',
    0,
    'primary',
    0.17,
    0.84,
    'Aligning IT with its contribution to the business.',
  ],
  [
    'Board experience',
    0,
    'tertiary',
    0.34,
    0.29,
    'Combining technology and business responsibility as CDO and board member at Borusan Mannesmann.',
  ],
  [
    'Business Case',
    0,
    'tertiary',
    0.14,
    0.53,
    'Justifying decisions through their expected value.',
  ],
  [
    'Growth',
    0,
    'tertiary',
    0.37,
    0.73,
    'Seeing technology as a foundation for further development.',
  ],
  [
    'Competitiveness',
    0,
    'tertiary',
    0.52,
    0.89,
    'Connecting technology with the company’s long-term position.',
  ],
  [
    'Transformation',
    0,
    'primary',
    0.81,
    0.84,
    'Developing the organisation and its systems together.',
  ],
  ['AI', 1, 'primary', 0.86, 0.18, 'Connecting new applications with processes and data.'],
  [
    'AI agents',
    1,
    'secondary',
    0.72,
    0.32,
    'Integrating AI agents in customer service and order processing into end-to-end processes.',
  ],
  [
    'Data architecture',
    1,
    'tertiary',
    0.53,
    0.27,
    'Creating a data architecture as the foundation for company-wide AI adoption.',
  ],
  [
    'SAP S/4HANA',
    1,
    'secondary',
    0.31,
    0.13,
    'Leading a group-wide SAP S/4HANA Enterprise Conversion at Hansgrohe.',
  ],
  [
    'Cloud',
    1,
    'tertiary',
    0.87,
    0.37,
    'Developing a cloud strategy and moving core applications to the cloud.',
  ],
  [
    'Cyber resilience',
    1,
    'secondary',
    0.66,
    0.7,
    'Embedding security and resilience in the organisation.',
  ],
  [
    'Enterprise architecture',
    1,
    'tertiary',
    0.77,
    0.53,
    'Connecting individual systems within a shared vision.',
  ],
  [
    'Automation',
    1,
    'secondary',
    0.91,
    0.68,
    'Considering repetitive work within the complete process.',
  ],
  ['People', 2, 'primary', 0.09, 0.37, 'Taking change forward together.'],
  [
    'Global teams',
    2,
    'secondary',
    0.52,
    0.75,
    'Connecting locations and perspectives through shared work.',
  ],
  [
    'Delivery Hubs',
    2,
    'tertiary',
    0.31,
    0.57,
    'Establishing a global delivery hub model as part of reshaping IT at Hansgrohe.',
  ],
  [
    'Industry 4.0',
    2,
    'secondary',
    0.17,
    0.69,
    'Connecting production with data and digital possibilities.',
  ],
  ['Supply Chain', 2, 'secondary', 0.69, 0.12, 'Considering processes across the value chain.'],
  ['IoT', 2, 'tertiary', 0.47, 0.39, 'Connecting physical processes and digital information.'],
  ['Change', 2, 'tertiary', 0.48, 0.6, 'Supporting people through organisational change.'],
  [
    'Networks',
    2,
    'tertiary',
    0.22,
    0.3,
    'Thinking about collaboration across organisational boundaries.',
  ],
];
