window.MUAMMER_TOPICS=[
  ['Leadership',0,'primary',.12,.18,"Setting a shared direction."],
  ["Strategy",0,'primary',.48,.10,"Thinking about technology and business objectives together."],
  ["value creation",0,'primary',.17,.84,"Aligning IT with its contribution to the business."],
  ["Board experience",0,'tertiary',.34,.29,"Combining technology and business responsibility as CDO and board member at Borusan Mannesmann."],
  ['Business Case',0,'tertiary',.14,.53,"Justifying decisions through their expected value."],
  ["Growth",0,'tertiary',.37,.73,"Seeing technology as a foundation for further development."],
  ["Competitiveness",0,'tertiary',.52,.89,"Connecting technology with the company’s long-term position."],
  ['Transformation',0,'primary',.81,.84,"Developing the organisation and its systems together."],
  ["AI",1,'primary',.86,.18,"Connecting new applications with processes and data."],
  ["AI agents",1,'secondary',.72,.32,"Integrating AI agents in customer service and order processing into end-to-end processes."],
  ["Data architecture",1,'tertiary',.53,.27,"Creating a data architecture as the foundation for company-wide AI adoption."],
  ['SAP S/4HANA',1,'secondary',.31,.13,"Leading a group-wide SAP S/4HANA Enterprise Conversion at Hansgrohe."],
  ['Cloud',1,'tertiary',.87,.37,"Developing a cloud strategy and moving core applications to the cloud."],
  ["Cyber resilience",1,'secondary',.66,.70,"Embedding security and resilience in the organisation."],
  ["Enterprise architecture",1,'tertiary',.77,.53,"Connecting individual systems within a shared vision."],
  ["Automation",1,'secondary',.91,.68,"Considering repetitive work within the complete process."],
  ["People",2,'primary',.09,.37,"Taking change forward together."],
  ["Global teams",2,'secondary',.52,.75,"Connecting locations and perspectives through shared work."],
  ['Delivery Hubs',2,'tertiary',.31,.57,"Establishing a global delivery hub model as part of reshaping IT at Hansgrohe."],
  ["Industry 4.0",2,'secondary',.17,.69,"Connecting production with data and digital possibilities."],
  ['Supply Chain',2,'secondary',.69,.12,"Considering processes across the value chain."],
  ['IoT',2,'tertiary',.47,.39,"Connecting physical processes and digital information."],
  ['Change',2,'tertiary',.48,.60,"Supporting people through organisational change."],
  ["Networks",2,'tertiary',.22,.30,"Thinking about collaboration across organisational boundaries."]
 ];
