window.MUAMMER_TOPICS=[
  ['Leadership',0,'primary',.12,.18,'Eine gemeinsame Richtung geben.'],
  ['Strategie',0,'primary',.48,.10,'Technologie und Unternehmensziele zusammendenken.'],
  ['Wertschöpfung',0,'primary',.17,.84,'IT am Beitrag zum Geschäft ausrichten.'],
  ['Vorstandserfahrung',0,'tertiary',.34,.29,'Als CDO und Vorstandsmitglied bei Borusan Mannesmann technologische und unternehmerische Verantwortung verbinden.'],
  ['Business Case',0,'tertiary',.14,.53,'Entscheidungen über ihren erwarteten Nutzen begründen.'],
  ['Wachstum',0,'tertiary',.37,.73,'Technologie als Grundlage weiterer Entwicklung betrachten.'],
  ['Wettbewerbsfähigkeit',0,'tertiary',.52,.89,'Technologie mit der langfristigen Position des Unternehmens verbinden.'],
  ['Transformation',0,'primary',.81,.84,'Organisation und Systeme gemeinsam weiterentwickeln.'],
  ['KI',1,'primary',.86,.18,'Neue Anwendungen mit Prozessen und Daten verbinden.'],
  ['KI-Agenten',1,'secondary',.72,.32,'KI-Agenten in Kundenservice und Auftragsabwicklung in durchgängige Prozesse einbinden.'],
  ['Datenarchitektur',1,'tertiary',.53,.27,'Datenarchitektur als Grundlage für den unternehmensweiten Einsatz von KI schaffen.'],
  ['SAP S/4HANA',1,'secondary',.31,.13,'Eine konzernweite SAP S/4HANA Enterprise Conversion bei Hansgrohe verantworten.'],
  ['Cloud',1,'tertiary',.87,.37,'Eine Cloud-Strategie entwickeln und zentrale Anwendungen in die Cloud überführen.'],
  ['Cyberresilienz',1,'secondary',.66,.70,'Sicherheit und Widerstandsfähigkeit in der Organisation verankern.'],
  ['Enterprise-Architektur',1,'tertiary',.77,.53,'Einzelne Systeme in einem gemeinsamen Zielbild verbinden.'],
  ['Automatisierung',1,'secondary',.91,.68,'Wiederkehrende Arbeit im Zusammenhang des Gesamtprozesses betrachten.'],
  ['Menschen',2,'primary',.09,.37,'Veränderung gemeinsam tragen.'],
  ['Globale Teams',2,'secondary',.52,.75,'Standorte und Perspektiven zu gemeinsamer Arbeit verbinden.'],
  ['Delivery Hubs',2,'tertiary',.31,.57,'Ein globales Delivery-Hub-Modell als Teil der IT-Neuausrichtung bei Hansgrohe verankern.'],
  ['Industrie 4.0',2,'secondary',.17,.69,'Produktion mit Daten und digitalen Möglichkeiten verbinden.'],
  ['Supply Chain',2,'secondary',.69,.12,'Prozesse entlang der Wertschöpfung zusammen betrachten.'],
  ['IoT',2,'tertiary',.47,.39,'Physische Prozesse und digitale Informationen verknüpfen.'],
  ['Change',2,'tertiary',.48,.60,'Menschen durch organisatorische Veränderung begleiten.'],
  ['Netzwerke',2,'tertiary',.22,.30,'Zusammenarbeit über organisatorische Grenzen hinweg denken.']
 ];
