window.MUAMMER_TOPICS = [
  ['Leadership', 0, 'primary', 0.12, 0.18, 'Eine gemeinsame Richtung geben.'],
  ['Strategie', 0, 'primary', 0.48, 0.1, 'Technologie und Unternehmensziele zusammendenken.'],
  ['Wertschöpfung', 0, 'primary', 0.17, 0.84, 'IT am Beitrag zum Geschäft ausrichten.'],
  [
    'Vorstandserfahrung',
    0,
    'tertiary',
    0.34,
    0.29,
    'Als CDO und Vorstandsmitglied bei Borusan Mannesmann technologische und unternehmerische Verantwortung verbinden.',
  ],
  [
    'Business Case',
    0,
    'tertiary',
    0.14,
    0.53,
    'Entscheidungen über ihren erwarteten Nutzen begründen.',
  ],
  [
    'Wachstum',
    0,
    'tertiary',
    0.37,
    0.73,
    'Technologie als Grundlage weiterer Entwicklung betrachten.',
  ],
  [
    'Wettbewerbsfähigkeit',
    0,
    'tertiary',
    0.52,
    0.89,
    'Technologie mit der langfristigen Position des Unternehmens verbinden.',
  ],
  [
    'Transformation',
    0,
    'primary',
    0.81,
    0.84,
    'Organisation und Systeme gemeinsam weiterentwickeln.',
  ],
  ['KI', 1, 'primary', 0.86, 0.18, 'Neue Anwendungen mit Prozessen und Daten verbinden.'],
  [
    'KI-Agenten',
    1,
    'secondary',
    0.72,
    0.32,
    'KI-Agenten in Kundenservice und Auftragsabwicklung in durchgängige Prozesse einbinden.',
  ],
  [
    'Datenarchitektur',
    1,
    'tertiary',
    0.53,
    0.27,
    'Datenarchitektur als Grundlage für den unternehmensweiten Einsatz von KI schaffen.',
  ],
  [
    'SAP S/4HANA',
    1,
    'secondary',
    0.31,
    0.13,
    'Eine konzernweite SAP S/4HANA Enterprise Conversion bei Hansgrohe verantworten.',
  ],
  [
    'Cloud',
    1,
    'tertiary',
    0.87,
    0.37,
    'Eine Cloud-Strategie entwickeln und zentrale Anwendungen in die Cloud überführen.',
  ],
  [
    'Cyberresilienz',
    1,
    'secondary',
    0.66,
    0.7,
    'Sicherheit und Widerstandsfähigkeit in der Organisation verankern.',
  ],
  [
    'Enterprise-Architektur',
    1,
    'tertiary',
    0.77,
    0.53,
    'Einzelne Systeme in einem gemeinsamen Zielbild verbinden.',
  ],
  [
    'Automatisierung',
    1,
    'secondary',
    0.91,
    0.68,
    'Wiederkehrende Arbeit im Zusammenhang des Gesamtprozesses betrachten.',
  ],
  ['Menschen', 2, 'primary', 0.09, 0.37, 'Veränderung gemeinsam tragen.'],
  [
    'Globale Teams',
    2,
    'secondary',
    0.52,
    0.75,
    'Standorte und Perspektiven zu gemeinsamer Arbeit verbinden.',
  ],
  [
    'Delivery Hubs',
    2,
    'tertiary',
    0.31,
    0.57,
    'Ein globales Delivery-Hub-Modell als Teil der IT-Neuausrichtung bei Hansgrohe verankern.',
  ],
  [
    'Industrie 4.0',
    2,
    'secondary',
    0.17,
    0.69,
    'Produktion mit Daten und digitalen Möglichkeiten verbinden.',
  ],
  [
    'Supply Chain',
    2,
    'secondary',
    0.69,
    0.12,
    'Prozesse entlang der Wertschöpfung zusammen betrachten.',
  ],
  ['IoT', 2, 'tertiary', 0.47, 0.39, 'Physische Prozesse und digitale Informationen verknüpfen.'],
  ['Change', 2, 'tertiary', 0.48, 0.6, 'Menschen durch organisatorische Veränderung begleiten.'],
  [
    'Netzwerke',
    2,
    'tertiary',
    0.22,
    0.3,
    'Zusammenarbeit über organisatorische Grenzen hinweg denken.',
  ],
];
