(function () {
  'use strict';

  const languages = {
    de: {
      explore: (topic) => topic + ' entdecken',
      connectionsGreeting: 'VERBINDUNGEN SCHAFFEN',
      connections: 'ZUSAMMENHÄNGE',
      motionReduced: 'BEWEGUNG — REDUZIERT',
      motionOff: 'BEWEGUNG — AUS',
      motionOn: 'BEWEGUNG — AN',
      topicCategories: [
        'UNTERNEHMERISCHE PERSPEKTIVE',
        'TECHNOLOGISCHE PERSPEKTIVE',
        'MENSCHEN & ZUSAMMENARBEIT',
      ],
      perspectives: ' PERSPEKTIVEN',
      nextCase: 'Weiter: ',
      chapterOverview: 'Kapitelübersicht öffnen',
      back: 'Zurück',
      home: 'Start',
      next: 'Weiter',
      start: 'Anfang',
      backHome: 'Zurück zum Start',
      backStart: 'Zurück zum Anfang',
      previousSection: 'Vorheriger Abschnitt: ',
      nextSection: 'Nächster Abschnitt',
      mobileChapterLabels: {
        'Ausgewählte Aufgaben': 'Verantwortung',
        'Perspektiven wechseln': 'Mein Weg',
        'Karriaro-Werkstatt': 'Karriaro',
      },
      finish: 'Abschließen',
      places: ' ORTE · ',
      chapters: ' STATIONEN',
      country: 'Deutschland',
      placeFallback: 'Ein Ort meines beruflichen Weges.',
      myJourney: 'MEIN WEG',
      startJourney: 'Weg beginnen',
      restartJourney: 'Zum Anfang',
      nextChapter: 'Nächste Station',
      careerChapters: 'Meine Stationen',
      welcomeLabels: ['Menschen.', 'Technologie.', 'Wertschöpfung.'],
    },
    en: {
      explore: (topic) => 'Explore ' + topic,
      connectionsGreeting: 'MAKING CONNECTIONS',
      connections: 'CONNECTIONS',
      motionReduced: 'MOTION — REDUCED',
      motionOff: 'MOTION — OFF',
      motionOn: 'MOTION — ON',
      topicCategories: [
        'ENTREPRENEURIAL PERSPECTIVE',
        'TECHNOLOGICAL PERSPECTIVE',
        'PEOPLE & COLLABORATION',
      ],
      perspectives: ' PERSPECTIVES',
      nextCase: 'Next: ',
      chapterOverview: 'Open chapter overview',
      back: 'Back',
      home: 'Home',
      next: 'Next',
      start: 'Start',
      backHome: 'Back to home',
      backStart: 'Back to the start',
      previousSection: 'Previous section: ',
      nextSection: 'Next section',
      mobileChapterLabels: {
        'Selected responsibilities': 'Responsibility',
        'Change perspectives': 'My journey',
        'Karriaro workshop': 'Karriaro',
      },
      finish: 'Finish',
      places: ' PLACES · ',
      chapters: ' CHAPTERS',
      country: 'Germany',
      placeFallback: 'A place along my professional journey.',
      myJourney: 'MY JOURNEY',
      startJourney: 'Start the journey',
      restartJourney: 'Back to the start',
      nextChapter: 'Next chapter',
      careerChapters: 'My career chapters',
      welcomeLabels: ['People.', 'Technology.', 'Value creation.'],
    },
  };

  window.ProfileText = languages[document.documentElement.lang] || languages.de;
})();
